version: '2'
services:
    jenkins:
        container_name: 'jenkins-pp'
        build:
            context: .
            dockerfile: Dockerfile.jenkins
        ports:
            - "8080:8080"
        volumes:
          - ./jenkins_home:/var/jenkins_home
